import canonicalLaneMathlib.AdmissibleClass
import HautevilleHouse.MaterialsEngineeringFractureMechanicsLemmaCanonicalLaneLean.FractureMechanicsLemmaAdmissibleClass
import HautevilleHouse.MaterialsEngineeringFractureMechanicsLemmaCanonicalLaneLean.LinearElasticFractureMechanicsBridge
import HautevilleHouse.MaterialsEngineeringFractureMechanicsLemmaCanonicalLaneLean.EnergyReleaseRateBridgingGate
import HautevilleHouse.MaterialsEngineeringFractureMechanicsLemmaCanonicalLaneLean.FractureMechanicsLemmaFinalTheorem
import HautevilleHouse.MaterialsEngineeringFractureMechanicsLemmaCanonicalLaneLean.CrackTipPlasticZoneCorrection
import HautevilleHouse.MaterialsEngineeringFractureMechanicsLemmaCanonicalLaneLean.FatigueCrackGrowthLaw

namespace HautevilleHouse
namespace MaterialsEngineeringFractureMechanicsLemmaCanonicalLaneLean

theorem entire_fracture_mechanics_lemma_closed_for (A : FractureAdmittedObject) :
    ConstrainedFractureMechanicsClosure A := by
  exact constrained_fracture_mechanics_endgame A

end MaterialsEngineeringFractureMechanicsLemmaCanonicalLaneLean
end HautevilleHouse